import type { Lang } from "./types.ts";
export type { Lang };

type Dict = Record<string, string>;

const en: Dict = {
  appName: "Osusume",
  tagline: "Anime picks from your own list — explained.",
  welcomeHint: "Your recommendations load automatically once you sign in with your AniList username.",
  go: "Get recommendations",
  booting: "Starting…",
  loadingProfile: "Reading your list…",
  loadingRecos: "Building recommendations… (first run ~1 min, then cached)",
  errUserNotFound: "User not found on AniList. Check the spelling.",
  errAnilistDown: "AniList is unreachable right now. Try again in a bit.",
  errGeneric: "Something went wrong. Try again.",
  loved: "You love",
  disliked: "You avoid",
  confidenceLow: "few scored entries — profile is rough",
  dropped: "Dropped",
  meanScore: "Mean score",
  sortFinal: "Best match",
  sortGem: "Best gem",
  sortAffinity: "Pure taste",
  llmOn: "LLM explanations: on",
  llmOff: "LLM explanations: off (local model not reachable)",
  localData: "Local data in use",
  localOn: "Local data — AniList unreachable",
  localBanner: "AniList is unreachable — you're seeing demo data, not your real list.",
  retryLive: "Retry live",
  updateAvailable: "Update {v} available — download",
  checkUpdates: "Check for updates",
  checking: "Checking…",
  upToDate: "You're up to date",
  localAuto: "Auto-switch to local data if AniList is down",
  emptyState: "Nothing to recommend — try a username with more scored entries.",
  affinity: "taste",
  quality: "quality",
  community: "community",
  badgeNextStep: "Next step",
  badgeEntryPoint: "Start here",
  badgeHiddenGem: "Hidden gem",
  badgeSpinOff: "Spin-off",
  moreInSeries: "{n} more in this series",
  whyBase: "Matches your taste for {dims}{studioPart}.{examplesPart}{gemPart}",
  whyNeutral: "Rated {avg}/100 on AniList by {pop} members.{gemPart}",
  whyExamples: " Seen in: {examples}.",
  whyEntryPoint: "It is also the first chapter of its series — a clean entry point.",
  whyGem: " Hidden gem: only {pop} members, {avg}/100 on AniList.",
  whyNotBase: "Shares {dims} you dropped or rated low{examplesPart}{droppedPart}.",
  whyNotExamples: " (e.g. {examples})",
  whyNotDropped: ", and you dropped {title} in this series",
  dimTag: "tags",
  dimGenre: "genres",
  dimStudio: "studio",
  dimEra: "era",
  langToggle: "Italiano",
  apiHint: "Everything runs locally: your list is read from AniList, explanations come from your own LLM server.",
  setupTitle: "Welcome — one-time setup",
  setupIntro: "Pick and download a local LLM to power the explanations. Recommended based on this machine:",
  setStep1: "Engine & model",
  setStep2: "Download",
  setStep3: "Ready",
  hwOs: "Operating system",
  hwChip: "Processor",
  hwRam: "RAM",
  recModel: "Recommended model",
  mlxOpt: "Apple MLX variant (8B)",
  mlxWarn: "Requires the PrismML fork of MLX (not merged upstream yet). The Bonsai-2 27B MLX pack runs only inside oMLX. Command to run it:",
  installCli: "Install LM Studio CLI (one click)",
  installingCli: "Installing LM Studio CLI…",
  backendMissing: "LM Studio CLI not found on this machine.",
  winFirstRun: "On Windows, open the LM Studio app once after install, then retry.",
  download: "Download model",
  downloading: "Downloading model…",
  downloadFailed: "Download failed — check the log below.",
  skipDownload: "Skip download (I'll use an existing model)",
  useCustom: "Use a custom OpenAI-compatible endpoint instead",
  customUrl: "Endpoint URL (e.g. http://127.0.0.1:11434/v1)",
  customUse: "Use this endpoint",
  skipSetup: "Skip setup (no LLM explanations)",
  finishTitle: "All set!",
  llmStarting: "Starting the LLM backend…",
  llmReady: "LLM backend is up.",
  llmOffNote: "LLM backend did not start — the app works fine without it. Check data/llm.log.",
  startUsing: "Enter the app",
  osMac: "macOS",
  osWin: "Windows",
  osLinux: "Linux",
  backendOmlx: "oMLX (Apple Silicon)",
  backendLms: "LM Studio",
  omlxFound: "oMLX detected — models on disk:",
  omlxStartNote: "The oMLX server will be started automatically.",
  navHome: "Home",
  navRecos: "Recommendations",
  navGems: "Hidden gems",
  navProfile: "Profile",
  navAvoid: "Avoid",
  navSettings: "Settings",
  setTitleLang: "Language",
  setTitleData: "Data source",
  setTitleUpd: "Updates",
  setTitleLlm: "AI model",
  on: "on",
  off: "off",
  currentVersion: "Version {v}",
  rerunSetup: "Run setup again",
  sectionPicks: "Featured picks",
  seeAll: "See all →",
  heroTop: "Top pick for {u}",
  heroOpen: "Open details",
  allRecos: "All recommendations",
  statMean: "Mean score · {n} rated",
  statDone: "Completed",
  statGems: "Gems found",
  statTop: "Highest match",
  stCur: "Watching",
  stPaused: "Paused",
  confOk: "Solid profile",
  gemsTitle: "Hidden gems",
  gemsSub: "Under-watched, well-rated, aligned with your taste — sorted by affinity.",
  profTitle: "Your taste profile",
  profSub: "Each dimension weighs real affinity from your scores, not declared genres.",
  avoidTitle: "Maybe avoid these",
  avoidSub: "Popular titles built on dimensions your scores already rejected.",
  fmtAll: "All",
  fmtMovie: "Movies",
  gemsOff: "All titles",
  gemsOnly: "Gems only",
  emptyBig: "No titles match these filters",
  emptySub: "Widen the selection: a match can hide behind a format.",
  resetFilters: "Reset filters",
  resultsLbl: "{n} titles",
  genreFilterOn: "Genre: {g} · remove",
  openAnilist: "Open on AniList",
  similar: "Similar to this",
  closeDialog: "Close details",
  carPrev: "Scroll back",
  carNext: "Scroll forward",
  kAffinity: "affinity",
  kMood: "continuity",
  kQuality: "quality",
  kCommunity: "community",
  whySrcLlm: "Explanation from your local model",
  whySrcLocal: "Explanation from your taste profile",
  llmWriting: "Your local model is writing the explanation…",
  chatTitle: "Chat",
  chatSub: "Talk with your local model about these recommendations",
  chatHello: "Ask anything about the recommendations: scores, affinity, why a title is here…",
  chatEmpty: "Get some recommendations first — then chat about them here.",
  chatNoLlm: "The local model is offline. Start it from the setup to use the chat.",
  chatPlaceholder: "Ask about your recommendations…",
  chatSend: "Send",
  lookupPlaceholder: "Search any anime to ask about it…",
  lookupGo: "Search",
  lookupNoRes: "No matches on AniList.",
  loginTitle: "Who's watching?",
  loginHint: "Sign in with your AniList username — everything stays local.",
  loginField: "AniList username",
  loginGo: "Enter",
  loginSwitch: "Switch user",
  searchAnime: "Search any anime…",
  searchAnimeNone: "No matches on AniList.",
  chatThinking: "The model is thinking…",
  secsShort: "{s}s",
  chatErr: "The model did not answer. Is it still running?",
  searchGo: "Search user",
  userField: "AniList username",
  searchErr: "User not found on AniList. Check the spelling.",
  coverOf: "Cover of {t}",
};

const it: Dict = {
  appName: "Osusume",
  tagline: "Anime consigliati dalla tua lista — con spiegazione.",
  welcomeHint: "I consigli arrivano da soli dopo l'accesso con il tuo username AniList.",
  go: "Consigliami",
  booting: "Avvio…",
  loadingProfile: "Leggo la tua lista…",
  loadingRecos: "Costruisco i consigli… (prima volta ~1 min, poi cache)",
  errUserNotFound: "Utente non trovato su AniList. Controlla la grafia.",
  errAnilistDown: "AniList non raggiungibile al momento. Riprova tra poco.",
  errGeneric: "Qualcosa è andato storto. Riprova.",
  loved: "Ami",
  disliked: "Eviti",
  confidenceLow: "pochi voti — profilo approssimativo",
  dropped: "Dropped",
  meanScore: "Voto medio",
  sortFinal: "Miglior match",
  sortGem: "Miglior gemma",
  sortAffinity: "Puro gusto",
  llmOn: "Spiegazioni LLM: attive",
  llmOff: "Spiegazioni LLM: offline (modello locale non raggiungibile)",
  localData: "Dati locali in uso",
  localOn: "Dati locali — AniList irraggiungibile",
  localBanner: "AniList è irraggiungibile — stai vedendo dati dimostrativi, non la tua lista vera.",
  retryLive: "Riprova live",
  updateAvailable: "Aggiornamento {v} disponibile — scarica",
  checkUpdates: "Controlla aggiornamenti",
  checking: "Verifica in corso…",
  upToDate: "Sei aggiornato",
  localAuto: "Passa automaticamente ai dati locali se AniList è giù",
  emptyState: "Niente da consigliare — prova uno username con più voti.",
  affinity: "gusto",
  quality: "qualità",
  community: "community",
  badgeNextStep: "Prossimo passo",
  badgeEntryPoint: "Inizia da qui",
  badgeHiddenGem: "Gemma nascosta",
  badgeSpinOff: "Spin-off",
  moreInSeries: "altri {n} della serie",
  whyBase: "Matcha il tuo gusto per {dims}{studioPart}.{examplesPart}{gemPart}",
  whyNeutral: "Valutato {avg}/100 su AniList da {pop} membri.{gemPart}",
  whyExamples: " Visto in: {examples}.",
  whyEntryPoint: "È anche il primo capitolo della serie — un buon punto d'ingresso.",
  whyGem: " Gemma nascosta: solo {pop} membri, {avg}/100 su AniList.",
  whyNotBase: "Condivide {dims} che hai droppato o votato basso{examplesPart}{droppedPart}.",
  whyNotExamples: " (es. {examples})",
  whyNotDropped: ", e in questa serie hai droppato {title}",
  dimTag: "tag",
  dimGenre: "generi",
  dimStudio: "studio",
  dimEra: "epoca",
  langToggle: "English",
  apiHint: "Tutto in locale: la lista arriva da AniList, le spiegazioni dal tuo server LLM.",
  setupTitle: "Benvenuto — configurazione una tantum",
  setupIntro: "Scegli e scarica un LLM locale per le spiegazioni. Consigliato in base a questa macchina:",
  setStep1: "Motore e modello",
  setStep2: "Download",
  setStep3: "Pronto",
  hwOs: "Sistema operativo",
  hwChip: "Processore",
  hwRam: "RAM",
  recModel: "Modello consigliato",
  mlxOpt: "Variante Apple MLX (8B)",
  mlxWarn: "Richiede il fork PrismML di MLX (non ancora mergiato upstream). Il pack MLX di Bonsai-2 27B gira solo dentro oMLX. Comando per usarlo:",
  installCli: "Installa LM Studio CLI (un click)",
  installingCli: "Installo la LM Studio CLI…",
  backendMissing: "CLI di LM Studio non trovata su questa macchina.",
  winFirstRun: "Su Windows, apri una volta l'app LM Studio dopo l'installazione, poi riprova.",
  download: "Scarica modello",
  downloading: "Scarico il modello…",
  downloadFailed: "Download fallito — controlla il log qui sotto.",
  skipDownload: "Salta il download (userò un modello già presente)",
  useCustom: "Usa invece un endpoint OpenAI-compatibile custom",
  customUrl: "URL endpoint (es. http://127.0.0.1:11434/v1)",
  customUse: "Usa questo endpoint",
  skipSetup: "Salta la configurazione (niente spiegazioni LLM)",
  finishTitle: "Tutto pronto!",
  llmStarting: "Avvio il backend LLM…",
  llmReady: "Backend LLM attivo.",
  llmOffNote: "Il backend LLM non si è avviato — l'app funziona lo stesso. Vedi data/llm.log.",
  startUsing: "Entra nell'app",
  osMac: "macOS",
  osWin: "Windows",
  osLinux: "Linux",
  backendOmlx: "oMLX (Apple Silicon)",
  backendLms: "LM Studio",
  omlxFound: "oMLX rilevato — modelli su disco:",
  omlxStartNote: "Il server oMLX verrà avviato automaticamente.",
  navHome: "Home",
  navRecos: "Consigli",
  navGems: "Gemme nascoste",
  navProfile: "Profilo",
  navAvoid: "Da evitare",
  navSettings: "Impostazioni",
  setTitleLang: "Lingua",
  setTitleData: "Sorgente dati",
  setTitleUpd: "Aggiornamenti",
  setTitleLlm: "Modello AI",
  on: "attivo",
  off: "disattivo",
  currentVersion: "Versione {v}",
  rerunSetup: "Ripeti la configurazione",
  sectionPicks: "Consigliati in primo piano",
  seeAll: "Vedi tutti →",
  heroTop: "Consiglio n.1 per {u}",
  heroOpen: "Apri il dettaglio",
  allRecos: "Tutti i consigli",
  statMean: "Voto medio · {n} votati",
  statDone: "Completati",
  statGems: "Gemme trovate",
  statTop: "Match più alto",
  stCur: "In corso",
  stPaused: "In pausa",
  confOk: "Profilo solido",
  gemsTitle: "Gemme nascoste",
  gemsSub: "Poco viste, ben votate, coerenti col tuo gusto — ordinate per affinità.",
  profTitle: "Il tuo profilo di gusto",
  profSub: "Ogni dimensione pesa l'affinità reale dei tuoi voti, non i generi dichiarati.",
  avoidTitle: "Forse da evitare",
  avoidSub: "Titoli popolari costruiti su dimensioni che i tuoi voti hanno già bocciato.",
  fmtAll: "Tutti",
  fmtMovie: "Film",
  gemsOff: "Tutti i titoli",
  gemsOnly: "Solo gemme",
  emptyBig: "Nessun titolo con questi filtri",
  emptySub: "Allarga la selezione: il match può nascondersi dietro un formato.",
  resetFilters: "Azzera i filtri",
  resultsLbl: "{n} titoli",
  genreFilterOn: "Genere: {g} · rimuovi",
  openAnilist: "Apri su AniList",
  similar: "Simili a questo",
  closeDialog: "Chiudi dettaglio",
  carPrev: "Scorri indietro",
  carNext: "Scorri avanti",
  kAffinity: "affinità",
  kMood: "continuità",
  kQuality: "qualità",
  kCommunity: "community",
  whySrcLlm: "Spiegazione dal tuo modello locale",
  whySrcLocal: "Spiegazione dal tuo profilo di gusto",
  llmWriting: "Il tuo modello locale sta scrivendo la spiegazione…",
  chatTitle: "Chat",
  chatSub: "Parla con il tuo modello locale di questi consigli",
  chatHello: "Chiedi pure dei consigli: punteggi, affinità, perché un titolo è qui…",
  chatEmpty: "Prima genera dei consigli — poi chatta di qui con il modello.",
  chatNoLlm: "Il modello locale è offline. Avvialo dal setup per usare la chat.",
  chatPlaceholder: "Chiedi dei tuoi consigli…",
  chatSend: "Invia",
  lookupPlaceholder: "Cerca qualsiasi anime di cui parlare…",
  lookupGo: "Cerca",
  lookupNoRes: "Nessun risultato su AniList.",
  loginTitle: "Chi sta guardando?",
  loginHint: "Accedi con il tuo username AniList — tutto resta in locale.",
  loginField: "Username AniList",
  loginGo: "Entra",
  loginSwitch: "Cambia utente",
  searchAnime: "Cerca qualsiasi anime…",
  searchAnimeNone: "Nessun risultato su AniList.",
  chatThinking: "Il modello sta pensando…",
  secsShort: "{s}s",
  chatErr: "Il modello non ha risposto. È ancora in esecuzione?",
  searchGo: "Cerca utente",
  userField: "Username AniList",
  searchErr: "Utente non trovato su AniList. Controlla la grafia.",
  coverOf: "Copertina di {t}",
};

const DICTS: Record<Lang, Dict> = { en, it };

/** Format a template with {placeholders}. */
export function tr(lang: Lang, key: string, params?: Record<string, string | number>): string {
  let s = DICTS[lang][key] ?? DICTS.en[key] ?? key;
  if (params) for (const [k, v] of Object.entries(params)) s = s.replaceAll(`{${k}}`, String(v));
  return s;
}
